apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-iii-config
  namespace: firefly-iii
data:
  SERVER_IP: "10.0.0.3"
  FIREFLY_NODEPORT: "31716"
  IMPORTER_NODEPORT: "32738"
  CLUSTER_DOMAIN: "cluster.local"
